# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fed5f738fc5fa33a0688d065e853568e083fe87eb14e6e6e2d3dbda1b043d411e5befce225222bc6185f29d464ba83bafb862b77f171f341372807b57264bd35

test:
  secret_key_base: 3fcef5ca534bdef58320982a1388cf21782db850e2323ad6b2611baed243e69cb5e071c53b095e3881093db56d85d7adb567f042af8ccc3168fedd0c90f80860

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
