# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7d8e856faef7d83a552cd037e93a2de270594f0e545ff04f9b33cffef7dabde46728ac8db338687f3f767515204096109120200d3379e3f5c2e5aafc65ad7ffc

test:
  secret_key_base: 1950d751d4dbca127985b5f9bc764492b124a36ec4b1524c2d88590c6f9eda8a002f7b4666cdb3b960e7cc47a661b6b69738804c487ec8fc0f06e9f2bec6ef7c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
